routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Categories
Route::resource('categories', 'CategoryController');
Route::get('category/data', 'CategoryController@categoryData')->name('category.data');

// Category Item Types
Route::resource('categoryitemtypes', 'CategoryItemTypeController');
Route::get('categoryitemtype/data', 'CategoryItemTypeController@categoryitemtypeData')->name('categoryitemtype.data');

// Item Types
Route::get('itemtype/data', 'ItemTypeController@itemtypeData')->name('itemtype.data');
Route::get('something','ItemTypeController@test');
Route::resource('itemtypes', 'ItemTypeController');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/ItemTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ItemType;
use DataTables;
use App\Category;
use App\CategoryItemType;

class ItemTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.itemtypes.index');
    }

    public function test()
    {
        dd(1);
    }

    public function itemtypeData(Request $request)
    {

        // $itemType = ItemType::all();
        // $categories = Category::all();
            // $itemType = Category::with()
        $itemType = ItemType::with('categories')->select('name')->first();
        dd($itemType->getCategories());
        dd($itemType);
        // $item = $categories->name;
        // dd($item);
        // dd($item);
        // $categories = Category::select('name')->get();
        return Datatables::of(ItemType::all())
        ->addColumn('action', function($itemtype){
            return view('admin.itemtypes.action', compact('itemtype'))->render();
        })
        ->editColumn('categoryid', function($itemtype) {
                    return $itemtype->categories->name;
                })
        ->make(true);


        // $categories = Category::get()->unique('categoryid')->values();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::select('id', 'name')->get();
        $categoryitemtypes = CategoryItemType::select('id', 'name')->get();
        return view('admin.itemtypes.create', compact('categories', 'categoryitemtypes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->input('withgender'));
        $this->validate($request, [
            'name' => 'required|string',
            'keyword' => 'required|string',
            'category' => 'required',
            'categoryitemtype' => 'required'
        ]);

        ItemType::create([
            'name' => $request->input('name'),
            'keyword' => $request->input('keyword'),
            'categoryid' => $request->input('category'),
            'categoryitemtypeid' => $request->input('categoryitemtype'),
        ]);
        
        return redirect()->route('itemtypes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $itemtypes = ItemType::where('id', '=', $id)->get();
        return view('admin.itemtypes.edit', compact('itemtypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string',
            'keyword' => 'required|string',
            'categoryid' => 'required',
            'categoryitemtypeid' => 'required'
        ]);

        $itemtype = ItemType::find($id);
        $itemtype->update($request->all());
        
        return redirect()->route('itemtypes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $itemtype = ItemType::find($id);
        $itemtype->delete();

        return back();
    }
}

resources/views/admin/itemtypes/action.blade.php
<a href="{{ route('itemtypes.edit', $itemtype->id) }}" class="btn btn-primary"> Edit </a>

<form action="{{ route('itemtypes.destroy', $itemtype->id) }}" method="POST" style="display: inline;" id="delete-form">
	{{ csrf_field() }}
	{{ method_field('DELETE') }}

	<button type="submit" class="btn btn-danger" id="delete-btn"> Delete </button>
</form>

resources/views/admin/itemtypes/create.blade.php
@extends('admin.layouts.master')

@section('title')

	<title>Item Type Register</title>

@endsection

@section('content')

	<div class="container">

		<h3>Item Type Registration</h3>
		<form action="{{ route('itemtypes.store') }}" method="POST">
			@csrf

			<div class="container" style="margin-top: 20px;">
				<label for="name" class="form-label">
					Item Type Name
				</label>
				<input type="text" class="form-control" name="name" required>
			</div>

			<div class="container" style="margin-top: 20px;">
				<label for="keyword" class="form-label">
					Keyword
				</label>
				<input type="text" class="form-control" name="keyword" required>
			</div>

			<div class="container" style="margin-top: 20px;">
				<label for="category" class="form-label">
					Category
				</label>
				<select name="category" class="form-control" id="" required>
					<option value="" disabled selected>Choose Category</option>
					@foreach($categories as $category)
						<option value="{{ $category->id }}">{{ $category->name }}</option>
					@endforeach
				</select>
			</div>

			<div class="container" style="margin-top: 20px;">
				<label for="categoryitemtype" class="form-label">
					Category Item Type
				</label>
				<select name="categoryitemtype" class="form-control" id="">
					<option value=""  disabled selected>Choose Item Type</option>
					<option value="0">None</option>
					@foreach($categoryitemtypes as $categoryitemtype)
						<option value="{{ $categoryitemtype->id }}">{{ $categoryitemtype->name }}</option>
					@endforeach
				</select>
			</div>

			<div class="container" style="margin-top: 20px;">
				<input type="submit" class="btn btn-primary" value="Register">
			</div>


			

		</form>
	</div>
@endsection

resources/views/admin/itemtypes/edit.blade.php
@extends('admin.layouts.master')

@section('title')

	<title>Category Edit</title>

@endsection

@section('content')

	<div class="container">

		<h3>Category Item Type Edit</h3>
		@foreach($categoryitemtypes as $categoryitemtype)
			<form action="{{ route('categoryitemtypes.update', $categoryitemtype->id) }}" method="POST">
				{{ csrf_field() }}
				{{ method_field('PATCH') }}

				<div class="container" style="margin-top: 20px;">
					<label for="name" class="form-label">
						Category Name
					</label>
					<input type="text" class="form-control" name="name" value="{{ old('name', $categoryitemtype->name) }}" required>
				</div>

				<div class="container" style="margin-top: 20px;">
					<input type="submit" class="btn btn-primary" value="Update">
				</div>

			</form>
		@endforeach
	</div>
@endsection

resources/views/admin/itemtypes/index.blade.php
@extends('admin.layouts.master')

@section('title')

	<title>Item Types</title>

@endsection

@section('content')
<div class="row">
    <div class="col-md-10">
    </div>
    <div class="col-md-2">
        <div class="container">
            <a href="{{ route('itemtypes.create') }}" class="btn btn-primary text-right">
                Register
            </a>
        </div>  
    </div>
</div>

<hr>
<!-- /.row -->
<div class="container">
    <h3>Item Types List</h3>
    <table class="table table-bordered" id="categoryitemtypes-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Item Type Name</th>
                <th>Keyword</th>
                <th>Category</th>
{{--                 <th>Category Item Type</th> --}}
                <th>Datetime</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>
@endsection

@push('script')
<script>
$(function() {
    $('#categoryitemtypes-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('itemtype.data') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'keyword', name: 'keyword' },
            { data: 'categoryid', name: 'categoryid' },
            // { data: 'categoryitemtypeid', name: 'categoryitemtypeid' },
            { data: 'created_at', name: 'created_at' },
            { data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
});
</script>
@endpush