routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Categories
Route::resource('categories', 'CategoryController');
Route::get('category/data', 'CategoryController@categoryData')->name('category.data');

// Category Item Types
Route::resource('categoryitemtypes', 'CategoryItemTypeController');
Route::get('categoryitemtype/data', 'CategoryItemTypeController@categoryitemtypeData')->name('categoryitemtype.data');

// Item Types
Route::get('itemtype/data', 'ItemTypeController@itemtypeData')->name('itemtype.data');
Route::get('something','ItemTypeController@test');
Route::resource('itemtypes', 'ItemTypeController');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/CategoryItemTypeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\CategoryItemType;
use DataTables;

class CategoryItemTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.categoryitemtypes.index');
    }

    public function categoryitemtypeData()
    {
        return Datatables::of(CategoryItemType::query())
        ->addColumn('action', function($categoryitemtype){
            return view('admin.categoryitemtypes.action', compact('categoryitemtype'))->render();
        })
        ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categoryitemtypes.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->input('withgender'));
        $this->validate($request, [
            'name' => 'required|string',
        ]);

        CategoryItemType::create([
            'name' => $request->input('name'),
        ]);
        
        return redirect()->route('categoryitemtypes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categoryitemtypes = CategoryItemType::where('id', '=', $id)->get();
        return view('admin.categoryitemtypes.edit', compact('categoryitemtypes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string',
        ]);

        $categoryitemtype = CategoryItemType::find($id);
        $categoryitemtype->update($request->all());
        
        return redirect()->route('categoryitemtypes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $categoryitemtype = CategoryItemType::find($id);
        $categoryitemtype->delete();

        return back();
    }
}

resources/views/admin/categoryitemtypes/action.blade.php
<a href="{{ route('categoryitemtypes.edit', $categoryitemtype->id) }}" class="btn btn-primary"> Edit </a>

<form action="{{ route('categoryitemtypes.destroy', $categoryitemtype->id) }}" method="POST" style="display: inline;" id="delete-form">
	{{ csrf_field() }}
	{{ method_field('DELETE') }}

	<button type="submit" class="btn btn-danger" id="delete-btn"> Delete </button>
</form>

resources/views/admin/categoryitemtypes/create.blade.php
@extends('admin.layouts.master')

@section('title')

	<title>Category Item Types Register</title>

@endsection

@section('content')

	<div class="container">

		<h3>Category Item Type Registration</h3>
		<form action="{{ route('categoryitemtypes.store') }}" method="POST">
			@csrf

			<div class="container" style="margin-top: 20px;">
				<label for="name" class="form-label">
					Category Item Type Name
				</label>
				<input type="text" class="form-control" name="name">
			</div>

			<div class="container" style="margin-top: 20px;">
				<input type="submit" class="btn btn-primary" value="Register">
			</div>


			

		</form>
	</div>
@endsection

resources/views/admin/categoryitemtypes/edit.blade.php
@extends('admin.layouts.master')

@section('title')

	<title>Category Edit</title>

@endsection

@section('content')

	<div class="container">

		<h3>Category Item Type Edit</h3>
		@foreach($categoryitemtypes as $categoryitemtype)
			<form action="{{ route('categoryitemtypes.update', $categoryitemtype->id) }}" method="POST">
				{{ csrf_field() }}
				{{ method_field('PATCH') }}

				<div class="container" style="margin-top: 20px;">
					<label for="name" class="form-label">
						Category Name
					</label>
					<input type="text" class="form-control" name="name" value="{{ old('name', $categoryitemtype->name) }}" required>
				</div>

				<div class="container" style="margin-top: 20px;">
					<input type="submit" class="btn btn-primary" value="Update">
				</div>

			</form>
		@endforeach
	</div>
@endsection

resources/views/admin/categoryitemtypes/index.blade.php
@extends('admin.layouts.master')

@section('title')

	<title>Category Item Types</title>

@endsection

@section('content')
<div class="row">
    <div class="col-md-10">
    </div>
    <div class="col-md-2">
        <div class="container">
            <a href="{{ route('categoryitemtypes.create') }}" class="btn btn-primary text-right">
                Register
            </a>
        </div>  
    </div>
</div>

<hr>
<!-- /.row -->
<div class="container">
    <h3>Category Item Types List</h3>
    <table class="table table-bordered" id="categoryitemtypes-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Category Item Type Name</th>
                <th>Datetime</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>
@endsection

@push('script')
<script>
$(function() {
    $('#categoryitemtypes-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('categoryitemtype.data') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'created_at', name: 'created_at' },
            { data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
});
</script>
@endpush