routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Categories
Route::resource('categories', 'CategoryController');
Route::get('category/data', 'CategoryController@categoryData')->name('category.data');

// Category Item Types
Route::resource('categoryitemtypes', 'CategoryItemTypeController');
Route::get('categoryitemtype/data', 'CategoryItemTypeController@categoryitemtypeData')->name('categoryitemtype.data');

// Item Types
Route::get('itemtype/data', 'ItemTypeController@itemtypeData')->name('itemtype.data');
Route::get('something','ItemTypeController@test');
Route::resource('itemtypes', 'ItemTypeController');




Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'name', 'keyword'
    ];

    public function itemtypes()
    {
        return $this->hasMany('App\ItemType');
    }

    public function getName()
    {
    	return $this->name;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use DataTables;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        return view('admin.categories.index');
    }

    public function categoryData()
    {
        return Datatables::of(Category::query())
        ->addColumn('action', function($category){
            return view('admin.categories.action', compact('category'))->render();
        })
        ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->input('withgender'));
        $this->validate($request, [
            'name' => 'required|string',
            'keyword' => 'required|string',
        ]);

        Category::create([
            'name' => $request->input('name'),
            'keyword' => $request->input('keyword'),
        ]);
        
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::where('id', '=', $id)->get();
        return view('admin.categories.edit', compact('categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required|string',
            'keyword' => 'required|string',
        ]);

        $category = Category::find($id);
        $category->update($request->all());
        
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        // $cover = Book::where('idx', '=', $id)->select('cover_photo')->get();
        // foreach ($cover as $photo) {
        //     $photo = $photo->cover_photo;
        // }
        // $coverphoto = '/photo/'.$photo;
        // $cover = Table::select('cover_photo')->where('idx', $id)->get();
        // unlink($_SERVER['DOCUMENT_ROOT'].$coverphoto);
        // Storage::delete($coverphoto);
        // DB::table('books')->where('idx', '=', $id)->delete();
        return back();
    }
}

resources/views/admin/categories/action.blade.php
<a href="{{ route('categories.edit', $category->id) }}" class="btn btn-primary"> Edit </a>

<form action="{{ route('categories.destroy', $category->id) }}" method="POST" style="display: inline;" id="delete-form">
	{{ csrf_field() }}
	{{ method_field('DELETE') }}

	<button type="submit" class="btn btn-danger" id="delete-btn"> Delete </button>
</form>

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.master')

@section('title')

	<title>Categories Register</title>

@endsection

@section('content')

	<div class="container">

		<h3>Categories Registration</h3>
		<form action="{{ route('categories.store') }}" method="POST">
			@csrf

			<div class="container" style="margin-top: 20px;">
				<label for="name" class="form-label">
					Category Name
				</label>
				<input type="text" class="form-control" name="name" required>
			</div>

			<div class="container" style="margin-top: 20px;">
				<label for="keyword" class="form-label">
					Keyword
				</label>
				<input type="text" class="form-control" name="keyword" required>
			</div>

			<div class="container" style="margin-top: 20px;">
				<input type="submit" class="btn btn-primary" value="Register">
			</div>


			

		</form>
	</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.master')

@section('title')

	<title>Category Edit</title>

@endsection

@section('content')

	<div class="container">

		<h3>Category Edit</h3>
		@foreach($categories as $category)
			<form action="{{ route('categories.update', $category->id) }}" method="POST">
				{{ csrf_field() }}
				{{ method_field('PATCH') }}

				<div class="container" style="margin-top: 20px;">
					<label for="name" class="form-label">
						Category Name
					</label>
					<input type="text" class="form-control" name="name" value="{{ old('name', $category->name) }}" required>
				</div>

				<div class="container" style="margin-top: 20px;">
					<label for="keyword" class="form-label">
						Keyword
					</label>
					<input type="text" class="form-control" name="keyword" value="{{ old('keyword', $category->keyword) }}" required>
				</div>

				<div class="container" style="margin-top: 20px;">
					<input type="submit" class="btn btn-primary" value="Update">
				</div>

			</form>
		@endforeach
	</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.master')

@section('title')
<title>Categories - Admin Panel</title>
@endsection

@section('content')
<div class="row">
	<div class="col-md-10">
	</div>
	<div class="col-md-2">
		<div class="container">
			<a href="{{ route('categories.create') }}" class="btn btn-primary text-right">
				Register
			</a>
		</div>	
	</div>
</div>

<hr>
<!-- /.row -->
<div class="container">
    <h3>Categories List</h3>
    <table class="table table-bordered" id="categories-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Category Name</th>
                <th>Keyword</th>
                <th>Datetime</th>
                <th></th>
            </tr>
        </thead>
    </table>
</div>
@endsection

@push('script')

<script>

$(function() {
    $('#categories-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('category.data') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'name', name: 'name' },
            { data: 'keyword', name: 'keyword' },
            { data: 'created_at', name: 'created_at' },
            { data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
});

</script>

@endpush